# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
site_name: Shen's Works
theme:
  features:
    - navigation.sections
  name: material
  palette:
  # Palette toggle for dark mode
  - scheme: slate
    accent: light blue
    primary: orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

  # Palette toggle for light mode
  - scheme: default
    accent: orange
    primary: black
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode

plugins:
  # Lets you zoom in on images
  - glightbox