# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Shen's Works
theme:
  name: material
  palette:
  # Palette toggle for dark mode
  - scheme: slate
    accent: light blue
    primary: orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

  # Palette toggle for light mode
  - scheme: default
    accent: orange
    primary: black
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
